version: '3'

volumes:
   minedata:

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MOTD: "Welcome to Docker Minecraft Server"
    volumes:      
      - minedata:/data
      