version: '3'

volumes:
  pihole_app:
  dns_config:

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    #hostname: ns.example.local
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Lisbon'
      WEBPASSWORD: 'your-secure-password'
    # Volumes store your data between container upgrades
    volumes:
      - 'pihole_app:/etc/pihole'
      - 'dns_config:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped