version: "3"

volumes:
    wordpress_data:
    wp_mysql_data:
    
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
    restart: always
    volumes: 
      - wordpress_data:/var/www/html     
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "wp-password"
      WORDPRESS_DB_DATABASE: "wordpress"
  mysql:  
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "wp-password"
    volumes:
      - wp_mysql_data:/var/lib/mysql

networks:  
  ohyeah:
    ipam:
      driver: default
      config:
        - subnet: "10.56.1.0/24"

