services:
  php:
    image: brufdev/many-notes:latest
    restart: unless-stopped
    volumes:
      - database:/var/www/html/database/sqlite
      - storage-logs:/var/www/html/storage/logs
      - storage-private:/var/www/html/storage/app/private
      - storage-public:/var/www/html/storage/app/public
      - storage-sessions:/var/www/html/storage/framework/sessions
    environment:
      - APP_URL=http://localhost:8080
      - ASSET_URL=http://localhost:8080
      - APP_TIMEZONE=Europe/Lisbon
      - PHP_POST_MAX_SIZE=1G
      - PHP_UPLOAD_MAX_FILE_SIZE=1G      
      #- GITHUB_CLIENT_ID=CLIENT_ID # change id
      #- GITHUB_CLIENT_SECRET=CLIENT_SECRET # change secret
      #- GITHUB_REDIRECT_URI=http://localhost/oauth/github/callback # change domain and provider
      - MAIL_MAILER=smtp
      - MAIL_HOST=127.0.0.1
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=many.notes@example.com
      - MAIL_FROM_NAME="Many Notes"      
    ports:
      - 80:8080

volumes:
  database:
  storage-logs:
  storage-private:
  storage-public:
  storage-sessions: