services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      # Set the timezone to your local timezone
      - TZ=Europe/Lisbon
    ports:
      - '8945:8945'
    volumes:
      - ./pinchflat/config:/config
      - ./pinchflat/downloads:/downloads
