volumes:
  sqlserver:

services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    container_name: MS-SQL-SERVER
    ports:
      - 1433:1433    
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=mssqlsapassword@1
      - MSSQL_PID=Standard
      - MSSQL_AGENT_ENABLED=true
    volumes:
      - sqlserver:/var/opt/mssql
