services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: p057gr35-pwd
      POSTGRES_HOST_AUTH_METHOD: trust

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb:latest
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:p057gr35-pwd@db:5432/?sslmode=disable
    ports:
      - 8081:8081

volumes:
  pgdata:
