version: '3'

volumes:
  actualbudget_data:

services:
  app:
    image: actualbudget/actual-server:latest
    restart: unless-stopped
    ports:
      - 5006:5006
    volumes:
      - actualbudget_data:/data
