volumes:
  minio_data:
  
services:
  minio:
    image: minio/minio
    volumes: 
      - "minio_data:/data"
    environment:
      - 'MINIO_ROOT_USER:minioadmin' 
      - 'MINIO_ROOT_PASSWORD:minioadmin' 
    command: server /data/minio/ --console-address :9001
    ports:
      - 5106:9000
      - 5112:9001
