services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_HTTP_API_UPDATE=false
      - WATCHTOWER_HTTP_API_METRICS=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080
