version: '3'

volumes:
  wikidata:

services:
  wikidocs:
    image: zavy86/wikidocs
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 2020:80
    volumes:
      - wikidata:/datasets
